In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
!pip install plotly

Requirement already satisfied: plotly in /Users/garvit/Desktop/website/website-env/lib/python3.10/site-packages (6.2.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/garvit/Desktop/website/website-env/lib/python3.10/site-packages (from plotly) (1.44.0)
Requirement already satisfied: packaging in /Users/garvit/Desktop/website/website-env/lib/python3.10/site-packages (from plotly) (24.2)

In [3]:
df = pd.read_csv("/Users/garvit/Desktop/website/6 - website Related/gurgaon_properties_missing_value_imputation.csv")

In [4]:
df.shape

(3554, 18)

In [5]:
df.head()

,property_type,society,sector,price,price_per_sqft,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,flat,signature global park 4,sector 36,0.82,7586.0,3.0,2.0,2,2.0,New Property,850.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
1,flat,smart world gems,sector 89,0.95,8597.0,2.0,2.0,2,4.0,New Property,1226.0,1.0,1.0,0.0,0.0,0.0,0.0,38.0
2,flat,breez global hill view,sohna road,0.32,5470.0,2.0,2.0,1,17.0,New Property,1000.0,0.0,0.0,0.0,0.0,0.0,0.0,49.0
3,flat,bestech park view sanskruti,sector 92,1.60,8020.0,3.0,4.0,3+,10.0,Relatively New,1615.0,0.0,1.0,0.0,0.0,1.0,1.0,174.0
4,flat,suncity avenue,sector 102,0.48,9023.0,2.0,2.0,1,5.0,Relatively New,582.0,0.0,0.0,1.0,0.0,0.0,0.0,159.0

In [6]:
latlong = pd.read_csv('latlong.csv')

In [7]:
latlong

          sector             coordinates
0       sector 1  28.3663° N, 76.9456° E
1       sector 2  28.5095° N, 77.0320° E
2       sector 3  28.4909° N, 77.0176° E
3       sector 4  28.4738° N, 77.0107° E
4       sector 5  28.4794° N, 77.0176° E
..           ...                     ...
124   sector 113  28.5287° N, 77.0233° E
125   sector 114  28.5334° N, 77.0118° E
126   sector 115  28.5385° N, 77.0061° E
127  gwal pahari  28.4484° N, 77.0210° E
128      manesar  28.3515° N, 76.9428° E

[129 rows x 2 columns]

In [8]:
latlong['latitude'] = latlong['coordinates'].str.split(',').str.get(0).str.split('°').str.get(0).astype('float')

In [9]:
latlong['longitude'] = latlong['coordinates'].str.split(',').str.get(1).str.split('°').str.get(0).astype('float')

In [10]:
latlong.head()

     sector             coordinates  latitude  longitude
0  sector 1  28.3663° N, 76.9456° E   28.3663    76.9456
1  sector 2  28.5095° N, 77.0320° E   28.5095    77.0320
2  sector 3  28.4909° N, 77.0176° E   28.4909    77.0176
3  sector 4  28.4738° N, 77.0107° E   28.4738    77.0107
4  sector 5  28.4794° N, 77.0176° E   28.4794    77.0176

In [11]:
new_df = df.merge(latlong,on='sector')

In [12]:
new_df.columns

Index(['property_type', 'society', 'sector', 'price', 'price_per_sqft',
       'bedRoom', 'bathroom', 'balcony', 'floorNum', 'agePossession',
       'built_up_area', 'study room', 'servant room', 'store room',
       'pooja room', 'others', 'furnishing_type', 'luxury_score',
       'coordinates', 'latitude', 'longitude'],
      dtype='object')

In [13]:
group_df = new_df.groupby('sector')[['price', 'price_per_sqft', 'built_up_area', 'latitude', 'longitude']].mean()

In [14]:
group_df['price_per_sqft'].max()

31881.85

In [15]:
group_df

                price  price_per_sqft  built_up_area  latitude  longitude
sector
gwal pahari  3.192222     9585.777778    3056.166667   28.4484    77.0210
manesar      0.962258     4608.064516    2027.367742   28.3515    76.9428
sector 1     1.860000     8249.833333    2327.833333   28.3663    76.9456
sector 10    2.092857    11866.571429    1908.857143   28.4537    77.0009
sector 102   1.696636    10603.822430    1556.130841   28.4750    76.9715
...               ...             ...            ...       ...        ...
sector 91    1.648235     7586.117647    2028.647059   28.4014    76.9225
sector 92    0.934000     5928.290000    1571.341800   28.4079    76.9153
sector 93    0.848889     8009.888889    1017.000000   28.4153    76.9326
sector 95    0.480545     5602.509091     995.981818   28.4172    76.9081
sector 99    1.008095     6412.166667    1364.214286   28.4640    76.9614

[101 rows x 5 columns]

In [16]:
import plotly.io as pio
pio.renderers.default = "browser"

In [17]:
fig = px.scatter_mapbox(group_df, lat="latitude", lon="longitude", color="price_per_sqft", size='built_up_area',
                  color_continuous_scale=px.colors.cyclical.IceFire, zoom=10,
                  mapbox_style="open-street-map",text=group_df.index)
fig.show()

/var/folders/gb/0twhhzk95yng3hgbcm16f5ph0000gn/T/ipykernel_23433/860414701.py:1: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

In [ ]:
new_df.to_csv('/Users/garvit/Desktop/website/datasets/data_viz.csv',index = False)

## Working on making word cloud